# Generated by Django 5.1.4 on 2025-01-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł albumu Skolima', max_length=100)),
                ('release_date', models.DateField(help_text='Data wydania albumu')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='Skolim', help_text='Artysta występujący', max_length=100)),
                ('location', models.CharField(help_text='Miejsce koncertu', max_length=200)),
                ('date', models.DateField(help_text='Data koncertu')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł piosenki Skolima', max_length=100)),
                ('duration', models.DurationField(help_text='Czas trwania piosenki')),
                ('release_date', models.DateField(help_text='Data wydania piosenki')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='kk_app.album')),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='kk_app.song')),
            ],
        ),
    ]
