# Generated by Django 5.1.4 on 2025-01-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(editable='False', help_text='Data wydania albumu'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(editable=False, help_text='Data wydania piosenki'),
        ),
    ]
