# Generated by Django 5.1.4 on 2025-01-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0003_rename_artist_collaboration_colaboration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='colaboration',
            new_name='collaboration',
        ),
    ]
