# Generated by Django 5.1.4 on 2025-01-25 16:11

import kk_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0006_alter_collaboration_song_title'),
    ]
