# Generated by Django 5.1.4 on 2025-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0007_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(editable=False, help_text='Data wydania albumu'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(help_text='Czas trwania piosenki'),
        ),
    ]
