# Generated by Django 5.1.4 on 2025-01-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0008_alter_album_release_date_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(help_text='Data wydania albumu'),
        ),
    ]
