# Generated by Django 5.1.4 on 2025-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0009_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(help_text='Czas trwania piosenki w formacie MM:SS'),
        ),
    ]
