# Generated by Django 5.1.4 on 2025-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0010_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(help_text='Czas trwania piosenki w formacie HH:MM:SS'),
        ),
    ]
