# Generated by Django 5.1.4 on 2025-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0011_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(help_text='Czas trwania piosenki w formacie HH:MM:SS', max_length=8),
        ),
    ]
