# Generated by Django 5.1.4 on 2025-01-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0012_alter_song_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=500)),
                ('pseudonim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
