# Generated by Django 5.1.2 on 2025-01-26 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kk_app', '0012_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(help_text='Czas trwania piosenki w formacie MM:SS', max_length=8, validators=[django.core.validators.RegexValidator(message='Czas trwania musi być w formacie MM:SS', regex='^[0-5][0-9]:[0-5][0-9]$')]),
        ),
    ]
